
AI = ["AI"]
Base64 = ["Base64"]
DateTime = ["Date & Time"]
Divar = ["Divar"]
DuckDuckGo = ["DuckDuckGo"]
FakeData = ["Fake data"]
GitHub = ["GitHub"]
AI_Image = ["AI Image Generator"]
Music = ["Music search"]
News = ["News"]
Icons = ["Icons search"]
Language = ["Language detect"]
HTML2JSON = ["Convert HTML to JSON"]
PyPi = ["PyPi projects search"]
Translate = ["Translate"]
Tron = ["Tron"]
