
AI = ["AI"]
Base64 = ["Base64"]
DateTime = ["Date & Time"]
DuckDuckGo = ["DuckDuckGo"]
FakeData = ["Fake data"]
GitHub = ["GitHub"]
AI_Image = ["AI Image Generator"]
Music = ["Music search"]
News = ["News"]
Translate = ["Translate"]
